app:
  kafka:
    events-topic: events-topic
    payments-topic: payments-topic
    payments-callback-topic: payments-callback-topic

server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  application:
    name: events-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
