server:
  port: 8081

logging:
  level:
    root: INFO

spring:
  application:
    name: events-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5433/events
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

