---
services:
  events-db:
    image: postgres:17
    container_name: events
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"  
    networks:
      - ticketing_platform_network

  users-db:
    image: postgres:17
    container_name: users
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"  
    networks:
      - ticketing_platform_network

  payments-db:
    image: postgres:17
    container_name: payments
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5435:5432"  
    networks:
      - ticketing_platform_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ticketing_platform_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    command:
      - bash
      - -c
      - |
          while ! nc -z localhost 9092; do sleep 1; done
          kafka-topics --bootstrap-server localhost:9092 --create --topic events-topic --partitions 1 --replication-factor 1
          kafka-topics --bootstrap-server localhost:9092 --create --topic payments-topic --partitions 1 --replication-factor 1
          exec /etc/confluent/docker/run
    networks:
      - ticketing_platform_network

networks:
  ticketing_platform_network:
    driver: bridge
