app:
  kafka:
    events-topic: events-topic

server:
  port: 8082

logging:
  level:
    root: INFO

spring:
  application:
    name: users-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5434/users
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
