app:
  kafka:
    payments-topic: payments-topic
    payments-callback-topic: payments-callback-topic

server:
  port: 8083

logging:
  level:
    root: INFO

spring:
  application:
    name: payments-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

stripe:
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

